### ISSUE TITLE
Electron version 5.0.0 doesn't do anything

### ISSUE THREAD

**Issue by pepa65** [rwynn/llave#1]
Unpacked the latest Electron release (electron-v5.0.0-beta.3-linux-x64.zip) and put **llave**'s `app.asar` and `app.asar.unpacked` directory into the `resources` directory of the Electron tree. When I run electron, the window showing up is called `llave` but is empty, the menu's are generic, and if I do anything with the menu's, like File>Quit or View>Reload, a Segmentation fault occurs.

I'm on Ubuntu 18.04.2, linux kernel 4.18.0-15-generic (but that shouldn't matter too much with Electron, right?)

**Comment by pepa65** [comment]
Tried this again with the Electron 3.1.4 release and everything works!
Better update the instructions in the readme to say not to get the latest release but the 3.1.4..!

**Comment by pepa65** [comment]
The app looks really nice and works well!
The only feedback I would give is, could it be possible for the URL field not to be mandatory? Now I have to put in a dummy character to get the entry accepted, and that shouldn't be necessary.

**Comment by rwynn** [comment]
Thanks for the feedback.  I haven't updated this application is a while so I imagine there could be some rough edges due to Electron progressing.  I've updated the README to reference the working version you mentioned.  

I agree that the URL should be optional.  Is that something that you would be able to submit a PR for?  I don't have much time to work on this application right now.  But I'd be happy to merge a PR if you can help.  

I'm not sure if the fix would be as easy as just editing [this function](https://github.com/rwynn/llave/blob/master/src/components/Add.js#L212).  There may be some additional logic that needs to be modified to account for a possible empty URL.

**Comment by pepa65** [comment]
It works, great! NIce to have an up to date ironclad binary used as well.

**Comment by pepa65** [comment]
It works, great!
